[tool.poetry]
name = "reboundtest"
version = "0.1.0"
description = ""
authors = ["Lukas Winkler <git@lw1.at>"]

[tool.poetry.dependencies]
python = "^3.7"
rebound = "^3.12.1"
matplotlib = "^3.2.1"
pyqt5 = "^5.14.1"
ipywidgets = "^7.5.1"
reboundx = "^3.0.4"
scipy = "^1.4.1"
graphviz = "^0.13.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
